export const initialValues = {
	id: null,
	name: "",
	description: "",
	category_id: "",
	selling_price: null,
	cost_price: null,
	crossed_price: null,
	quantity: null,
	sku: null,
	status: "active",
	options: null,
	variants: null,
	images: null,
};
